apiVersion: apps/v1
kind: Deployment
metadata:
  name: DEPLOYMENT_NAME
  namespace: NAMESPACE
  labels:
    app: PROJECT
spec:
  selector:
    matchLabels:
      project: PROJECT
  template:
    metadata:
      namespace: NAMESPACE
      labels:
        project: PROJECT
    spec:
      containers:
         - name: PROJECT
           image: REGISTRY_HOSTNAME/PROJECT:TAG_VERSION
           ports:
             - containerPort: PORT_CONTAINER

           env:
             - name: OAUTH_GOOGLE_CLIENT_ID
               valueFrom:
                 secretKeyRef:
                   name: back-404-production-config-secret
                   key: OAUTH_GOOGLE_CLIENT_ID
             - name: OAUTH_GOOGLE_CLIENT_SECRET
               valueFrom:
                 secretKeyRef:
                   name: back-404-production-config-secret
                   key: OAUTH_GOOGLE_CLIENT_SECRET
