apiVersion: apps/v1
kind: Deployment
metadata:
  name: DEPLOYMENT_NAME
  namespace: NAMESPACE
  labels:
    app: PROJECT
spec:
  selector:
    matchLabels:
      project: PROJECT
  template:
    metadata:
      namespace: NAMESPACE
      labels:
        project: PROJECT
    spec:
      containers:
        - name: PROJECT
          image: REGISTRY_HOSTNAME/PROJECT:TAG_VERSION
          ports:
            - containerPort: PORT_CONTAINER

          env:
            - name: OAUTH_GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: back-404-production-config-secret
                  key: OAUTH_GOOGLE_CLIENT_ID
            - name: ENV
              valueFrom:
                secretKeyRef:
                  name: back-404-production-config-secret
                  key: ENV
            - name: GOOGLE_CAPTURE_SECRET
              valueFrom:
                secretKeyRef:
                  name: back-404-production-config-secret
                  key: GOOGLE_CAPTURE_SECRET
            - name: CAPTURE_SITE_KEY
              valueFrom:
                secretKeyRef:
                  name: back-404-production-config-secret
                  key: CAPTURE_SITE_KEY
            - name: DATABASE_URL_FOR_TESTS
              valueFrom:
                secretKeyRef:
                  name: back-404-production-config-secret
                  key: DATABASE_URL_FOR_TESTS
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: back-404-production-config-secret
                  key: DATABASE_URL
            - name: ACCESS_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: back-404-production-config-secret
                  key: ACCESS_TOKEN_SECRET
            - name: REFRESH_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: back-404-production-config-secret
                  key: REFRESH_TOKEN_SECRET
            - name: EMAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: back-404-production-config-secret
                  key: EMAIL_PASSWORD
            - name: EMAIL_USER
              valueFrom:
                secretKeyRef:
                  name: back-404-production-config-secret
                  key: EMAIL_USER
            - name: EMAIL_SERVICE
              valueFrom:
                secretKeyRef:
                  name: back-404-production-config-secret
                  key: EMAIL_SERVICE
            - name: BASIC_AUTH_USERNAME
              valueFrom:
                secretKeyRef:
                  name: back-404-production-config-secret
                  key: BASIC_AUTH_USERNAME
            - name: BASIC_AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: back-404-production-config-secret
                  key: BASIC_AUTH_PASSWORD
            - name: OAUTH_GITHUB_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: back-404-production-config-secret
                  key: OAUTH_GITHUB_CLIENT_SECRET
            - name: OAUTH_GITHUB_REDIRECT_URL
              valueFrom:
                secretKeyRef:
                  name: back-404-production-config-secret
                  key: OAUTH_GITHUB_REDIRECT_URL
            - name: OAUTH_GOOGLE_REDIRECT_URL
              valueFrom:
                secretKeyRef:
                  name: back-404-production-config-secret
                  key: OAUTH_GOOGLE_REDIRECT_URL
            - name: OAUTH_GITHUB_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: back-404-production-config-secret
                  key: OAUTH_GITHUB_CLIENT_ID
            - name: OAUTH_GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: back-404-production-config-secret
                  key: OAUTH_GOOGLE_CLIENT_SECRET
