version: '3.8'

services:
  postgresql:
    image: postgres:latest
    environment:
      POSTGRES_USER: userdb
      POSTGRES_PASSWORD: qwerty123
      POSTGRES_DB: postgresdb
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U userdb"]
      interval: 10s
      retries: 5

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - backend

  rabbitmq:
    image: rabbitmq:management
    environment:
      RABBITMQ_DEFAULT_USER: rmquser
      RABBITMQ_DEFAULT_PASS: rmqpassword
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - backend

volumes:
  postgres_data:
  mongo_data:

networks:
  backend:
