version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-app
    env_file: .env
    environment:
      POSTGRES_HOST: db
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
      APP_PORT: ${PORT}
    ports:
      - '9876:9876'
    depends_on:
      - db
    volumes:
      - ./src:/app/src
    networks:
      - docker-compose-network

  db:
    image: postgres
    container_name: postgres-inc
    restart: always
    ports:
      - '5433:5432'
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - docker-compose-network

networks:
  docker-compose-network:
    driver: bridge

volumes:
  pgdata:
