export enum QUEUE_TOKEN {
  FILES_SERVICE = 'FILES_SERVICE',
  NOTICE_SERVICE = 'NOTICE_SERVICE',
}
export enum QUEUE_NAME {
  FILES = 'RMQ_FILES_QUEUE',
  NOTICE = 'RMQ_NOTICE_QUEUE',
  USER = 'RMQ_USERS_QUEUE',
  EVENTS = 'RMQ_EVENTS_QUEUE',
}
export const USERS_QUEUE = QUEUE_NAME.USER;
export const FILES_QUEUE = QUEUE_NAME.FILES;
export const EVENTS_QUEUE = QUEUE_NAME.EVENTS;

export enum SERVICE_TOKEN {
  FILES = 'FILES_SERVICE',
  TCP_FILES = 'TCP_FILES_SERVICE',
  USERS = 'USERS_SERVICE',
  NOTICE = 'NOTICE_SERVICE',
  EVENTS = 'EVENTS_SERVICE',
}

export const TCP_FILES_SERVICE = SERVICE_TOKEN.TCP_FILES;

export const FILES_SERVICE = SERVICE_TOKEN.FILES;
export const USERS_SERVICE = SERVICE_TOKEN.USERS;
export const EVENTS_SERVICE = SERVICE_TOKEN.EVENTS;

export enum EVENT_NAME {
  FILE_UPLOAD = 'upload_file',
  PROFILE_IMAGE_UPLOAD = 'upload_profile_image',
  POST_CREATED = 'upload_post_image',
}
export const enum EVENT_COMMANDS {
  IMAGES_PROCESSED = 'images_processed',
  PROFILE_IMAGES_COMPLETED = 'profile_images_completed',
  FILE_UPLOAD = 'FILE_UPLOAD',
  PROFILE_IMAGE_UPLOAD = 'upload_profile_image',
  POST_IMAGE_UPLOAD = 'upload_post_image',
  IMAGES_DELIVERED = 'images_delivered',
  OUTBOX_FILE = 'outbox_file',
  PROFILE_IMAGES_PROCESSED = 'profile_images_processed',
  POST_IMAGES_PROCESSED = 'post_images_processed',
}

export const POST_IMAGE_UPLOAD = EVENT_COMMANDS.POST_IMAGE_UPLOAD;
export const PROFILE_IMAGE_UPLOAD = EVENT_COMMANDS.PROFILE_IMAGE_UPLOAD;
export const IMAGES_COMPLETED = EVENT_COMMANDS.PROFILE_IMAGES_COMPLETED;
export const IMAGES_DELIVERED = EVENT_COMMANDS.PROFILE_IMAGES_COMPLETED;
export const IMAGES_PROCESSED = EVENT_COMMANDS.IMAGES_PROCESSED;
export const PROFILE_IMAGES_PROCESSED = EVENT_COMMANDS.PROFILE_IMAGES_PROCESSED;
export const POST_IMAGES_PROCESSED = EVENT_COMMANDS.POST_IMAGES_PROCESSED;
export const OUTBOX_FILE = EVENT_COMMANDS.OUTBOX_FILE;
